import { createContext, useContext, useEffect, useState, ReactNode } from "react";

export type Lang = "pt" | "en";

type Dict = Record<string, string>;

const translations: Record<Lang, Dict> = {
  pt: {
    // Generic
    "common.back": "Voltar",
    "common.loading": "A carregar...",
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.all": "Todos",
    "common.continue": "Continuar",
    "common.done": "Concluído",
    "common.optional": "Opcional",
    "common.required": "Obrigatório",
    "common.minutesShort": "min",
    "common.notFound": "Não encontrado",
    "common.error": "Erro",

    // Nav (BottomNav)
    "nav.home": "Início",
    "nav.trainings": "Treinos",
    "nav.progress": "Progresso",
    "nav.leaderboard": "Ranking",
    "nav.profile": "Perfil",

    // Home
    "home.greeting": "Olá",
    "home.dailyGoal": "Objetivo diário",
    "home.weeklyChallenge": "Desafio semanal",
    "home.todayPicks": "Sugestões de hoje",
    "home.browseAll": "Ver todos os treinos",
    "home.followUs": "Segue-nos",

    // Trainings list
    "trainings.title": "Biblioteca de Treinos",
    "trainings.subtitle": "Encontra a tua próxima sessão",
    "trainings.empty": "Nenhuma sessão corresponde a estes filtros.",
    "trainings.premium": "Premium",
    "trainings.unlockPremium": "Desbloquear com Premium →",

    // Training detail
    "training.equipment": "Equipamento",
    "training.drills": "Exercícios",
    "training.finish": "Terminar sessão",
    "training.tickAll": "Marca todos os exercícios",
    "training.premiumContent": "Conteúdo Premium",
    "training.unlock": "Desbloqueia este treino",
    "training.subscribeCta": "Subscreve por 10€/mês para aceder ao vídeo e a todos os exercícios premium.",
    "training.becomePremium": "Tornar-me Premium",
    "training.lockedDrills": "exercício(s) premium bloqueado(s)",
    "training.subscribeToUnlock": "Subscreve para desbloquear →",
    "training.unlockWithPremium": "Desbloquear com Premium",
    "training.introVideo": "Explicação",
    "training.exerciseVideo": "Exercício",
    "training.watchDrill": "Ver vídeo",
    "training.hideVideo": "Esconder",
    "training.markDone": "Marcar como feito",
    "training.markUndone": "Marcar como não feito",

    // Complete session
    "complete.selfAssessment": "Auto-avaliação",
    "complete.howWasIt": "Como correu?",
    "complete.overallFeel": "Sensação geral",
    "complete.rateYourself": "Avalia-te",
    "complete.scale": "(0–10)",
    "complete.notes": "Notas",
    "complete.notesPlaceholder": "O que correu bem, o que não correu...",
    "complete.submitEarn": "Submeter e ganhar",
    "complete.xp": "XP",
    "complete.sessionComplete": "Sessão concluída!",
    "complete.coachFeedback": "Feedback do treinador",
    "complete.seeProgress": "Ver progresso",
    "complete.doneBtn": "Concluído",
    "complete.xpEarned": "XP ganho",
    "complete.streakDays": "Sequência",
    "complete.saveFailed": "Falha ao guardar",
    "complete.couldNotSave": "Não foi possível guardar a sessão",

    // Progress
    "progress.title": "Progresso",
    "progress.subtitle": "A tua jornada como guarda-redes",
    "progress.totalXp": "XP total",
    "progress.sessions": "Sessões",
    "progress.bestStreak": "Melhor sequência",
    "progress.timeTrained": "Tempo treinado",
    "progress.level": "Nível",
    "progress.last4Weeks": "Últimas 4 semanas",
    "progress.skillProfile": "Perfil de habilidades",
    "progress.badges": "Distintivos",

    // Goals
    "goals.title": "Os meus objetivos",
    "goals.empty": "Ainda não tens objetivos. Adiciona um abaixo!",
    "goals.adminEmpty": "Ainda não há objetivos disponíveis. Cria o primeiro!",
    "goals.add": "Adicionar objetivo",
    "goals.create": "Criar objetivo",
    "goals.new": "Novo objetivo",
    "goals.titleField": "Título",
    "goals.titlePlaceholder": "Ex: Treinar 3x por semana",
    "goals.descField": "Descrição",
    "goals.descPlaceholder": "Detalhes do objetivo (opcional)",
    "goals.metric": "Métrica",
    "goals.metric.sessions": "Sessões",
    "goals.metric.xp": "XP",
    "goals.metric.minutes": "Minutos",
    "goals.metric.streak": "Sequência (dias)",
    "goals.target": "Valor alvo",
    "goals.period": "Período",
    "goals.period.daily": "Diário",
    "goals.period.weekly": "Semanal",
    "goals.period.monthly": "Mensal",
    "goals.period.all_time": "Sempre",
    "goals.xpReward": "Recompensa XP",
    "goals.activate": "Ativar",
    "goals.activated": "Objetivo adicionado!",
    "goals.removed": "Objetivo removido",
    "goals.created": "Objetivo criado!",
    "goals.deleted": "Modelo apagado",
    "goals.available": "Objetivos disponíveis",
    "goals.completed": "Concluído",
    "goals.progress": "{current} / {target}",
    "goals.deleteConfirm": "Apagar este modelo de objetivo?",
    "goals.adminBadge": "Admin",

    // Leaderboard
    "leaderboard.title": "Ranking",
    "leaderboard.subtitle": "Compete com guarda-redes de todo o mundo",
    "leaderboard.global": "Global",
    "leaderboard.myLevel": "Meu nível",
    "leaderboard.you": "(tu)",
    "leaderboard.empty": "Ainda não há guarda-redes — sê o primeiro!",
    "leaderboard.lvShort": "Nv",

    // Profile
    "profile.fallbackName": "Guarda-redes",
    "profile.statXp": "XP",
    "profile.statStreak": "Sequência",
    "profile.statBest": "Melhor",
    "profile.myGoal": "O meu objetivo",
    "profile.managePremium": "Gerir subscrição",
    "profile.becomePremium": "Tornar-me Premium · 10€/mês",
    "profile.editProfile": "Editar perfil",
    "profile.admin": "Admin",
    "profile.signOut": "Terminar sessão",

    // Onboarding
    "onb.stepOf": "Passo {current} de {total}",
    "onb.setupKit": "Configura o teu equipamento",
    "onb.levelTitle": "Qual é o teu nível?",
    "onb.ageTitle": "Escalão etário",
    "onb.handTitle": "Mão dominante",
    "onb.styleTitle": "Estilo de jogo",
    "onb.styleHelp": "Obrigatório. Escolhe um ou mais que te descrevam.",
    "onb.stylePickAtLeastOne": "Escolhe pelo menos um estilo.",
    "onb.goalTitle": "O teu objetivo de treino",
    "onb.goalHelp": "Opcional. Ajuda-nos a recomendar sessões.",
    "onb.goalLabel": "Objetivo",
    "onb.goalPlaceholder": "Ser mais confiante nos cruzamentos...",
    "onb.back": "Voltar",
    "onb.continue": "Continuar",
    "onb.start": "Começar a treinar",
    "onb.styleRequired": "Estilo de jogo obrigatório",
    "onb.styleRequiredDesc": "Escolhe pelo menos um estilo de jogo.",
    "onb.allSet": "Tudo pronto! 🧤",
    "onb.allSetDesc": "Vamos treinar.",
    "onb.couldNotSave": "Não foi possível guardar",
    // Levels
    "level.beginner": "Iniciante",
    "level.intermediate": "Intermédio",
    "level.advanced": "Avançado",
    "level.pro": "Profissional",
    // Hands
    "hand.right": "Direita",
    "hand.left": "Esquerda",
    "hand.both": "Ambas",
    // Playing styles
    "style.libero": "GR líbero",
    "style.aerial": "Forte no jogo aéreo",
    "style.quick_exits": "GR rápido nas saídas",
    "style.imposing": "Imponente",
    "style.quick_reflexes": "Reflexos rápidos",
    "style.strong_hands": "Mãos fortes",

    // Subscription
    "sub.title": "GK Premium",
    "sub.subtitle": "Desbloqueia todos os treinos e acelera a tua evolução",
    "sub.activeTitle": "Subscrição ativa",
    "sub.activeDesc": "Tens acesso completo a todos os exercícios premium.",
    "sub.nextRenewal": "Próxima renovação:",
    "sub.cancelAtEnd": "A subscrição termina no fim do período atual.",
    "sub.monthlyPlan": "Plano mensal",
    "sub.month": "/mês",
    "sub.subscribeBtn": "Subscrever 10€/mês",
    "sub.opening": "A abrir...",
    "sub.cancelAnytime": "Cancela a qualquer momento. Pagamento seguro processado pela Paddle.",
    "sub.checkoutError": "Erro a abrir checkout: ",
    "sub.benefit1": "Acesso a todos os treinos premium",
    "sub.benefit2": "Vídeos exclusivos de drills avançados",
    "sub.benefit3": "Planos personalizados por nível",
    "sub.benefit4": "Sem anúncios e sem limites diários",
    "sub.benefit5": "Suporte prioritário",
    "sub.benefit6": "Cancela quando quiseres",
    "sub.testBanner": "Pagamentos em modo de teste. Usa o cartão",
    "sub.testBannerSuffix": "para testar.",

    // Auth
    "auth.tagline": "Treina como um profissional. Defende como uma lenda.",
    "auth.signup": "Registar",
    "auth.signin": "Entrar",
    "auth.gkName": "Nome de guarda-redes",
    "auth.email": "Email",
    "auth.password": "Palavra-passe",
    "auth.startTraining": "Começar a treinar",
    "auth.login": "Entrar",
    "auth.checkDetails": "Verifica os teus dados",
    "auth.welcome": "Bem-vindo ao GK Performance Hub 🧤",
    "auth.welcomeDesc": "Vamos configurar o teu perfil.",
    "auth.error": "Erro de autenticação",
    "auth.somethingWrong": "Algo correu mal",

    // Admin
    "admin.title": "Admin",
    "admin.subtitle": "Gerir treinos e vídeos",
    "admin.new": "Novo",
    "admin.empty": "Ainda não existem treinos. Cria o primeiro!",
    "admin.makeFree": "Tornar gratuito",
    "admin.makePremium": "Tornar Premium",
    "admin.draft": "rascunho",
    "admin.deleteConfirm": "Apagar este treino?",
    "admin.deleted": "Treino apagado",
    "admin.madePremium": "Tornado Premium 👑",
    "admin.madeFree": "Tornado gratuito",
    "admin.noPermission": "Não tens permissões para aceder a esta área.",
    "admin.noAdminsYet": "Ainda não existe nenhum administrador.",
    "admin.claimText": "Como és o primeiro a entrar nesta área, podes reclamar o papel de administrador para ti.",
    "admin.claimBtn": "Tornar-me administrador",
    "admin.claimed": "És agora administrador 🛡️",
    "admin.claimError": "Não foi possível tornar-te admin: ",
    // Admin form
    "adminForm.editTitle": "Editar treino",
    "adminForm.newTitle": "Novo treino",
    "adminForm.titleLabel": "Título *",
    "adminForm.descLabel": "Descrição",
    "adminForm.categoryLabel": "Categoria *",
    "adminForm.categoryPlaceholder": "Escolher",
    "adminForm.levelLabel": "Nível",
    "adminForm.durationLabel": "Duração (min)",
    "adminForm.xpLabel": "XP recompensa",
    "adminForm.video": "Vídeo principal (exercício)",
    "adminForm.introVideo": "Vídeo de explicação (curto)",
    "adminForm.introVideoHint": "Opcional. Vídeo curto que explica o exercício antes do vídeo principal.",
    "adminForm.removeIntro": "Remover",
    "adminForm.replaceFile": "Substituir ficheiro",
    "adminForm.drillIntroVideo": "Vídeo de explicação do exercício",
    "adminForm.drillExerciseVideo": "Vídeo do exercício",
    "adminForm.uploading": "A carregar...",
    "adminForm.chooseFile": "Escolher ficheiro de vídeo",
    "adminForm.embedUrl": "URL embed",
    "adminForm.embedHint": "Usa o link de \"embed\" (não o link normal de partilha).",
    "adminForm.equipmentLabel": "Equipamento (separado por vírgulas)",
    "adminForm.equipmentPlaceholder": "bola, cones, parede",
    "adminForm.drills": "Exercícios",
    "adminForm.drillsHint": "Marca individualmente quais exercícios são premium (úteis em treinos gratuitos com partes pagas).",
    "adminForm.add": "Adicionar",
    "adminForm.drillTitle": "Título",
    "adminForm.drillReps": "Reps",
    "adminForm.drillPremium": "Exercício Premium",
    "adminForm.drillFree": "Exercício gratuito",
    "adminForm.published": "Publicado",
    "adminForm.publishedDesc": "Visível para todos os utilizadores",
    "adminForm.premiumExercise": "Exercício Premium",
    "adminForm.premiumExerciseDesc": "Apenas utilizadores com subscrição podem aceder",
    "adminForm.saveChanges": "Guardar alterações",
    "adminForm.create": "Criar treino",
    "adminForm.titleRequired": "Título obrigatório",
    "adminForm.videoRequired": "Adiciona um vídeo",
    "adminForm.categoryRequired": "Escolhe uma categoria",
    "adminForm.fileTooBig": "Ficheiro demasiado grande (máx 200MB).",
    "adminForm.uploadFailed": "Falha no upload: ",
    "adminForm.videoLoaded": "Vídeo carregado",
    "adminForm.created": "Treino criado",
    "adminForm.updated": "Treino atualizado",

    // NotFound
    "nf.title": "Página não encontrada",
    "nf.return": "Voltar ao início",

    // Language
    "lang.pt": "Português",
    "lang.en": "English",
  },
  en: {
    "common.back": "Back",
    "common.loading": "Loading...",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.all": "All",
    "common.continue": "Continue",
    "common.done": "Done",
    "common.optional": "Optional",
    "common.required": "Required",
    "common.minutesShort": "min",
    "common.notFound": "Not found",
    "common.error": "Error",

    "nav.home": "Home",
    "nav.trainings": "Trainings",
    "nav.progress": "Progress",
    "nav.leaderboard": "Leaderboard",
    "nav.profile": "Profile",

    "home.greeting": "Hey",
    "home.dailyGoal": "Daily goal",
    "home.weeklyChallenge": "Weekly challenge",
    "home.todayPicks": "Today's picks",
    "home.browseAll": "Browse all trainings",
    "home.followUs": "Follow us",

    "trainings.title": "Training Library",
    "trainings.subtitle": "Find your next session",
    "trainings.empty": "No sessions match those filters.",
    "trainings.premium": "Premium",
    "trainings.unlockPremium": "Unlock with Premium →",

    "training.equipment": "Equipment",
    "training.drills": "Drills",
    "training.finish": "Finish session",
    "training.tickAll": "Tick all drills",
    "training.premiumContent": "Premium Content",
    "training.unlock": "Unlock this training",
    "training.subscribeCta": "Subscribe for €10/month to access the video and all premium drills.",
    "training.becomePremium": "Become Premium",
    "training.lockedDrills": "premium drill(s) locked",
    "training.subscribeToUnlock": "Subscribe to unlock →",
    "training.unlockWithPremium": "Unlock with Premium",
    "training.introVideo": "Explanation",
    "training.exerciseVideo": "Exercise",
    "training.watchDrill": "Watch video",
    "training.hideVideo": "Hide",
    "training.markDone": "Mark as done",
    "training.markUndone": "Mark as not done",

    "complete.selfAssessment": "Self-assessment",
    "complete.howWasIt": "How did it go?",
    "complete.overallFeel": "Overall feel",
    "complete.rateYourself": "Rate yourself",
    "complete.scale": "(0–10)",
    "complete.notes": "Notes",
    "complete.notesPlaceholder": "What worked, what didn't...",
    "complete.submitEarn": "Submit & earn",
    "complete.xp": "XP",
    "complete.sessionComplete": "Session complete!",
    "complete.coachFeedback": "Coach feedback",
    "complete.seeProgress": "See progress",
    "complete.doneBtn": "Done",
    "complete.xpEarned": "XP earned",
    "complete.streakDays": "Streak",
    "complete.saveFailed": "Save failed",
    "complete.couldNotSave": "Could not save session",

    "progress.title": "Progress",
    "progress.subtitle": "Your goalkeeping journey",
    "progress.totalXp": "Total XP",
    "progress.sessions": "Sessions",
    "progress.bestStreak": "Best streak",
    "progress.timeTrained": "Time trained",
    "progress.level": "Level",
    "progress.last4Weeks": "Last 4 weeks",
    "progress.skillProfile": "Skill profile",
    "progress.badges": "Badges",

    // Goals
    "goals.title": "My goals",
    "goals.empty": "You don't have any goals yet. Add one below!",
    "goals.adminEmpty": "No goals available yet. Create the first one!",
    "goals.add": "Add goal",
    "goals.create": "Create goal",
    "goals.new": "New goal",
    "goals.titleField": "Title",
    "goals.titlePlaceholder": "E.g. Train 3x per week",
    "goals.descField": "Description",
    "goals.descPlaceholder": "Goal details (optional)",
    "goals.metric": "Metric",
    "goals.metric.sessions": "Sessions",
    "goals.metric.xp": "XP",
    "goals.metric.minutes": "Minutes",
    "goals.metric.streak": "Streak (days)",
    "goals.target": "Target value",
    "goals.period": "Period",
    "goals.period.daily": "Daily",
    "goals.period.weekly": "Weekly",
    "goals.period.monthly": "Monthly",
    "goals.period.all_time": "All time",
    "goals.xpReward": "XP reward",
    "goals.activate": "Activate",
    "goals.activated": "Goal added!",
    "goals.removed": "Goal removed",
    "goals.created": "Goal created!",
    "goals.deleted": "Template deleted",
    "goals.available": "Available goals",
    "goals.completed": "Completed",
    "goals.progress": "{current} / {target}",
    "goals.deleteConfirm": "Delete this goal template?",
    "goals.adminBadge": "Admin",

    "leaderboard.title": "Leaderboard",
    "leaderboard.subtitle": "Compete with keepers worldwide",
    "leaderboard.global": "Global",
    "leaderboard.myLevel": "My level",
    "leaderboard.you": "(you)",
    "leaderboard.empty": "No keepers yet — be the first!",
    "leaderboard.lvShort": "Lv",

    "profile.fallbackName": "Keeper",
    "profile.statXp": "XP",
    "profile.statStreak": "Streak",
    "profile.statBest": "Best",
    "profile.myGoal": "My goal",
    "profile.managePremium": "Manage subscription",
    "profile.becomePremium": "Become Premium · €10/month",
    "profile.editProfile": "Edit profile",
    "profile.admin": "Admin",
    "profile.signOut": "Sign out",

    "onb.stepOf": "Step {current} of {total}",
    "onb.setupKit": "Set up your kit",
    "onb.levelTitle": "What's your level?",
    "onb.ageTitle": "Age group",
    "onb.handTitle": "Dominant hand",
    "onb.styleTitle": "Playing style",
    "onb.styleHelp": "Required. Pick one or more that describe you.",
    "onb.stylePickAtLeastOne": "Pick at least one style.",
    "onb.goalTitle": "Your training goal",
    "onb.goalHelp": "Optional. Helps us recommend sessions.",
    "onb.goalLabel": "Goal",
    "onb.goalPlaceholder": "Be more confident on crosses...",
    "onb.back": "Back",
    "onb.continue": "Continue",
    "onb.start": "Start training",
    "onb.styleRequired": "Playing style required",
    "onb.styleRequiredDesc": "Pick at least one playing style.",
    "onb.allSet": "All set! 🧤",
    "onb.allSetDesc": "Let's get you training.",
    "onb.couldNotSave": "Could not save",
    "level.beginner": "Beginner",
    "level.intermediate": "Intermediate",
    "level.advanced": "Advanced",
    "level.pro": "Pro",
    "hand.right": "Right",
    "hand.left": "Left",
    "hand.both": "Both",
    "style.libero": "Sweeper-keeper",
    "style.aerial": "Strong in the air",
    "style.quick_exits": "Quick off the line",
    "style.imposing": "Imposing presence",
    "style.quick_reflexes": "Quick reflexes",
    "style.strong_hands": "Strong hands",

    "sub.title": "GK Premium",
    "sub.subtitle": "Unlock all trainings and accelerate your progress",
    "sub.activeTitle": "Subscription active",
    "sub.activeDesc": "You have full access to all premium drills.",
    "sub.nextRenewal": "Next renewal:",
    "sub.cancelAtEnd": "Subscription ends at the end of the current period.",
    "sub.monthlyPlan": "Monthly plan",
    "sub.month": "/month",
    "sub.subscribeBtn": "Subscribe €10/month",
    "sub.opening": "Opening...",
    "sub.cancelAnytime": "Cancel anytime. Secure payment processed by Paddle.",
    "sub.checkoutError": "Checkout error: ",
    "sub.benefit1": "Access to all premium trainings",
    "sub.benefit2": "Exclusive videos of advanced drills",
    "sub.benefit3": "Personalised plans by level",
    "sub.benefit4": "No ads, no daily limits",
    "sub.benefit5": "Priority support",
    "sub.benefit6": "Cancel anytime",
    "sub.testBanner": "Payments in test mode. Use card",
    "sub.testBannerSuffix": "to test.",

    "auth.tagline": "Train like a pro. Save like a legend.",
    "auth.signup": "Sign up",
    "auth.signin": "Log in",
    "auth.gkName": "Goalkeeper name",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.startTraining": "Start training",
    "auth.login": "Log in",
    "auth.checkDetails": "Check your details",
    "auth.welcome": "Welcome to GK Performance Hub 🧤",
    "auth.welcomeDesc": "Let's set up your profile.",
    "auth.error": "Auth error",
    "auth.somethingWrong": "Something went wrong",

    "admin.title": "Admin",
    "admin.subtitle": "Manage trainings and videos",
    "admin.new": "New",
    "admin.empty": "No trainings yet. Create the first one!",
    "admin.makeFree": "Make free",
    "admin.makePremium": "Make Premium",
    "admin.draft": "draft",
    "admin.deleteConfirm": "Delete this training?",
    "admin.deleted": "Training deleted",
    "admin.madePremium": "Marked as Premium 👑",
    "admin.madeFree": "Marked as free",
    "admin.noPermission": "You don't have permission to access this area.",
    "admin.noAdminsYet": "There are no administrators yet.",
    "admin.claimText": "Since you're the first to enter this area, you can claim the admin role for yourself.",
    "admin.claimBtn": "Make me an administrator",
    "admin.claimed": "You're now an administrator 🛡️",
    "admin.claimError": "Could not make you admin: ",
    "adminForm.editTitle": "Edit training",
    "adminForm.newTitle": "New training",
    "adminForm.titleLabel": "Title *",
    "adminForm.descLabel": "Description",
    "adminForm.categoryLabel": "Category *",
    "adminForm.categoryPlaceholder": "Choose",
    "adminForm.levelLabel": "Level",
    "adminForm.durationLabel": "Duration (min)",
    "adminForm.xpLabel": "XP reward",
    "adminForm.video": "Main video (exercise)",
    "adminForm.introVideo": "Explanation video (short)",
    "adminForm.introVideoHint": "Optional. Short clip explaining the drill — plays before the main exercise video.",
    "adminForm.removeIntro": "Remove",
    "adminForm.replaceFile": "Replace file",
    "adminForm.drillIntroVideo": "Drill explanation video",
    "adminForm.drillExerciseVideo": "Drill exercise video",
    "adminForm.uploading": "Uploading...",
    "adminForm.chooseFile": "Choose video file",
    "adminForm.embedUrl": "Embed URL",
    "adminForm.embedHint": "Use the \"embed\" link (not the regular share link).",
    "adminForm.equipmentLabel": "Equipment (comma separated)",
    "adminForm.equipmentPlaceholder": "ball, cones, wall",
    "adminForm.drills": "Drills",
    "adminForm.drillsHint": "Mark individual drills as premium (useful for free trainings with paid parts).",
    "adminForm.add": "Add",
    "adminForm.drillTitle": "Title",
    "adminForm.drillReps": "Reps",
    "adminForm.drillPremium": "Premium drill",
    "adminForm.drillFree": "Free drill",
    "adminForm.published": "Published",
    "adminForm.publishedDesc": "Visible to all users",
    "adminForm.premiumExercise": "Premium training",
    "adminForm.premiumExerciseDesc": "Only subscribed users can access",
    "adminForm.saveChanges": "Save changes",
    "adminForm.create": "Create training",
    "adminForm.titleRequired": "Title is required",
    "adminForm.videoRequired": "Add a video",
    "adminForm.categoryRequired": "Choose a category",
    "adminForm.fileTooBig": "File too large (max 200MB).",
    "adminForm.uploadFailed": "Upload failed: ",
    "adminForm.videoLoaded": "Video uploaded",
    "adminForm.created": "Training created",
    "adminForm.updated": "Training updated",

    "nf.title": "Oops! Page not found",
    "nf.return": "Return to Home",

    "lang.pt": "Português",
    "lang.en": "English",
  },
};

interface Ctx {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<Ctx | undefined>(undefined);

const STORAGE_KEY = "gk-lang";

function detectInitial(): Lang {
  if (typeof window === "undefined") return "pt";
  const stored = localStorage.getItem(STORAGE_KEY) as Lang | null;
  if (stored === "pt" || stored === "en") return stored;
  const nav = navigator.language?.toLowerCase() ?? "";
  return nav.startsWith("en") ? "en" : "pt";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(detectInitial);

  useEffect(() => {
    document.documentElement.lang = lang;
    localStorage.setItem(STORAGE_KEY, lang);
  }, [lang]);

  const setLang = (l: Lang) => setLangState(l);

  const t = (key: string, vars?: Record<string, string | number>) => {
    let str = translations[lang][key] ?? translations.pt[key] ?? key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
