-- Make the training-videos bucket private.
UPDATE storage.buckets SET public = false WHERE id = 'training-videos';

-- Drop the public direct-read policy that exposed every video file by URL.
DROP POLICY IF EXISTS "Training videos public direct read" ON storage.objects;

-- Drop legacy "authenticated upload" policy (admins-only is the active rule).
DROP POLICY IF EXISTS "Authenticated upload training videos" ON storage.objects;

-- No SELECT policy is created here intentionally:
-- the bucket is now private and all reads must go through signed URLs
-- generated by the SECURITY DEFINER edge function (service-role), which
-- enforces subscription / admin / public-training checks server-side.